USE Clinic

ALTER DATABASE Clinic
SET ALLOW_SNAPSHOT_ISOLATION ON
SET TRANSACTION ISOLATION LEVEL SNAPSHOT
BEGIN TRAN
Select * from Doctor
UPDATE Doctor SET Salary = Salary+15 WHERE DoctorID = 1
Select * from Doctor
COMMIT TRAN

